//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class s12667Entities : DbContext
    {
        public s12667Entities()
            : base("name=s12667Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TIN_Kategoria> TIN_Kategoria { get; set; }
        public virtual DbSet<TIN_Opinia> TIN_Opinia { get; set; }
        public virtual DbSet<TIN_Tagi> TIN_Tagi { get; set; }
        public virtual DbSet<TIN_Wydarzenie> TIN_Wydarzenie { get; set; }
    }
}
